### ISSUE TITLE
 Unable to extract Initial JS player n function name

### ISSUE THREAD

**Issue by Kibahor** [poseidon-code/ytmp3-dl#1]
Hi,
I wanted to use your project but it appear that the same error happened and two different pc and os.
Download one song work but not with a playlist ...
I try essential and base release and also build on windows and linux and the result is the same.

` .\ytmp3-dl.exe -l 6 -d './dl' 'https://www.youtube.com/playlist?list=PLWA7yojbv0ofzDLyswGSABK0XXXXX'
WARNING: [youtube:tab] YouTube said: INFO - Unavailable videos are hidden
WARNING: [youtube:tab] YouTube said: INFO - Unavailable videos will be hidden during playback
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = YIjUZKks2K2Ff4fw8 ; player = https://www.youtube.com/s/player/c81bbb4a/player_ias.vflset/en_US/base.js
oaV_3n3uIjA: Traceback (most recent call last):
  File "yt_dlp\extractor\youtube.py", line 1881, in _decrypt_nsig
  File "yt_dlp\extractor\youtube.py", line 1902, in _extract_n_function
  File "yt_dlp\extractor\youtube.py", line 1890, in _extract_n_function_name
  File "yt_dlp\extractor\common.py", line 1171, in _search_regex
yt_dlp.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS player n function name\x1b[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.`

**Comment by poseidon-code** [comment]
Currently both the shipped binaries does not have the playlist download support.
To download playlists one need to use the program as a script _(Check [Script Usage](https://github.com/poseidon-code/ytmp3-dl#script-like-usage))_ 

Also needs to change the yt-dlp options inside the `ytmp3-dl.py` file:

0. After setting up script like usage, proceed.
1. open `ytmp3-dl.py`
2. go to `line:204`
3. change **from** `"noplaylist": True` **to** `"noplaylist": False`
4. using this setting, `ytmp3-dl` will run not run parallel _(i.e. `-l` will not work for musics inside the playlist)_.
5. run like: `python ytmp3-dl.py -d "./dl" <playlist url>`

**PS:** playlist download & sectioned music download will be implemented soon

**Comment by Kibahor** [comment]
Ok thanks, 
Instead of use this project, i had directly used yt-dlp.
Thanks for the fast reply, I will know what to do next time 👌
